// <auto-generated />
using System;
using CGG.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CGG.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304061034_RemoveDescriptionFromAiPromptTemplate")]
    partial class RemoveDescriptionFromAiPromptTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CGG.Core.Entities.AIRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AIRecommendations");
                });

            modelBuilder.Entity("CGG.Core.Entities.AiLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("int");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromptText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("SurveyResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserSurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MemberId");

                    b.HasIndex("PromptTemplateId");

                    b.HasIndex("RequestType");

                    b.HasIndex("Status");

                    b.HasIndex("SurveyResultId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSurveyId");

                    b.HasIndex("MemberId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AiLogs");
                });

            modelBuilder.Entity("CGG.Core.Entities.AiPromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<int?>("Model")
                        .HasColumnType("int");

                    b.Property<string>("OutputFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("SurveyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDefault");

                    b.ToTable("AiPromptTemplates");
                });

            modelBuilder.Entity("CGG.Core.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("CGG.Core.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDefault");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("CGG.Core.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("CGG.Core.Entities.MemberRole", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId", "RoleId");

                    b.HasIndex("MemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("MemberRoles");
                });

            modelBuilder.Entity("CGG.Core.Entities.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("CGG.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CGG.Core.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("CGG.Core.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DefaultLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("SurveyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultLanguageId");

                    b.HasIndex("IsActive");

                    b.HasIndex("SurveyType");

                    b.HasIndex("SurveyType", "Version")
                        .IsUnique();

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PurposeCategory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("RequiresAiAnalysis")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PurposeCategory");

                    b.HasIndex("QuestionType");

                    b.HasIndex("RequiresAiAnalysis");

                    b.HasIndex("StepId");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "SortOrder");

                    b.ToTable("SurveyQuestionOptions");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestionOptionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OptionId", "LanguageId")
                        .IsUnique();

                    b.ToTable("SurveyQuestionOptionTranslations");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("QuestionId", "LanguageId")
                        .IsUnique();

                    b.ToTable("SurveyQuestionTranslations");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStep")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("int");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurveyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CurrentStep");

                    b.HasIndex("FamilyId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MemberId");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyType");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("SurveyResults");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AiPromptTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("SkipAiProcessing")
                        .HasColumnType("bit");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AiPromptTemplateId");

                    b.HasIndex("SurveyId", "StepNumber")
                        .IsUnique();

                    b.ToTable("SurveySteps");
                });

            modelBuilder.Entity("CGG.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CGG.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AgeAddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FamilyId");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasFilter("[MemberId] IS NOT NULL");

                    b.HasIndex("Role");

                    b.HasIndex("SchoolId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CGG.Core.Entities.UserSurvey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurveyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SurveyId");

                    b.HasIndex("UserId", "SurveyType");

                    b.ToTable("UserSurveys");
                });

            modelBuilder.Entity("CGG.Core.Entities.UserSurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserSurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserSurveyId", "StepNumber", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserSurveyAnswers_Survey_Step_Question");

                    b.ToTable("UserSurveyAnswers");
                });

            modelBuilder.Entity("CGG.Core.Entities.AIRecommendation", b =>
                {
                    b.HasOne("CGG.Core.Entities.User", "User")
                        .WithMany("AIRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CGG.Core.Entities.AiLog", b =>
                {
                    b.HasOne("CGG.Core.Entities.Member", "Member")
                        .WithMany("AiLogs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CGG.Core.Entities.AiPromptTemplate", "PromptTemplate")
                        .WithMany("AiLogs")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CGG.Core.Entities.SurveyResult", "SurveyResult")
                        .WithMany("AiLogs")
                        .HasForeignKey("SurveyResultId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CGG.Core.Entities.User", "User")
                        .WithMany("AiLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CGG.Core.Entities.UserSurvey", "UserSurvey")
                        .WithMany("AiLogs")
                        .HasForeignKey("UserSurveyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Member");

                    b.Navigation("PromptTemplate");

                    b.Navigation("SurveyResult");

                    b.Navigation("User");

                    b.Navigation("UserSurvey");
                });

            modelBuilder.Entity("CGG.Core.Entities.AiPromptTemplate", b =>
                {
                    b.HasOne("CGG.Core.Entities.User", "CreatedBy")
                        .WithMany("CreatedPromptTemplates")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CGG.Core.Entities.Member", b =>
                {
                    b.HasOne("CGG.Core.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGG.Core.Entities.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("CGG.Core.Entities.Member", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CGG.Core.Entities.MemberRole", b =>
                {
                    b.HasOne("CGG.Core.Entities.Member", "Member")
                        .WithMany("MemberRoles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGG.Core.Entities.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CGG.Core.Entities.Survey", b =>
                {
                    b.HasOne("CGG.Core.Entities.Language", "DefaultLanguage")
                        .WithMany()
                        .HasForeignKey("DefaultLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultLanguage");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("CGG.Core.Entities.SurveyStep", "Step")
                        .WithMany("Questions")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Step");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestionOption", b =>
                {
                    b.HasOne("CGG.Core.Entities.SurveyQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestionOptionTranslation", b =>
                {
                    b.HasOne("CGG.Core.Entities.Language", "Language")
                        .WithMany("OptionTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CGG.Core.Entities.SurveyQuestionOption", "Option")
                        .WithMany("Translations")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestionTranslation", b =>
                {
                    b.HasOne("CGG.Core.Entities.Language", "Language")
                        .WithMany("QuestionTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CGG.Core.Entities.SurveyQuestion", "Question")
                        .WithMany("Translations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyResult", b =>
                {
                    b.HasOne("CGG.Core.Entities.Family", "Family")
                        .WithMany("SurveyResults")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CGG.Core.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CGG.Core.Entities.Member", "Member")
                        .WithMany("SurveyResults")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CGG.Core.Entities.Survey", "Survey")
                        .WithMany("SurveyResults")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CGG.Core.Entities.User", "User")
                        .WithMany("SurveyResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Family");

                    b.Navigation("Language");

                    b.Navigation("Member");

                    b.Navigation("Survey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyStep", b =>
                {
                    b.HasOne("CGG.Core.Entities.AiPromptTemplate", "AiPromptTemplate")
                        .WithMany("SurveySteps")
                        .HasForeignKey("AiPromptTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CGG.Core.Entities.Survey", "Survey")
                        .WithMany("Steps")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiPromptTemplate");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("CGG.Core.Entities.Transaction", b =>
                {
                    b.HasOne("CGG.Core.Entities.Family", "Family")
                        .WithMany("Transactions")
                        .HasForeignKey("FamilyId");

                    b.HasOne("CGG.Core.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CGG.Core.Entities.User", b =>
                {
                    b.HasOne("CGG.Core.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CGG.Core.Entities.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Family");

                    b.Navigation("School");
                });

            modelBuilder.Entity("CGG.Core.Entities.UserSurvey", b =>
                {
                    b.HasOne("CGG.Core.Entities.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CGG.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CGG.Core.Entities.UserSurveyAnswer", b =>
                {
                    b.HasOne("CGG.Core.Entities.UserSurvey", "UserSurvey")
                        .WithMany("Answers")
                        .HasForeignKey("UserSurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSurvey");
                });

            modelBuilder.Entity("CGG.Core.Entities.AiPromptTemplate", b =>
                {
                    b.Navigation("AiLogs");

                    b.Navigation("SurveySteps");
                });

            modelBuilder.Entity("CGG.Core.Entities.Family", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("SurveyResults");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CGG.Core.Entities.Language", b =>
                {
                    b.Navigation("OptionTranslations");

                    b.Navigation("QuestionTranslations");
                });

            modelBuilder.Entity("CGG.Core.Entities.Member", b =>
                {
                    b.Navigation("AiLogs");

                    b.Navigation("MemberRoles");

                    b.Navigation("SurveyResults");
                });

            modelBuilder.Entity("CGG.Core.Entities.Role", b =>
                {
                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("CGG.Core.Entities.School", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CGG.Core.Entities.Survey", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("SurveyResults");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestion", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyQuestionOption", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyResult", b =>
                {
                    b.Navigation("AiLogs");
                });

            modelBuilder.Entity("CGG.Core.Entities.SurveyStep", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CGG.Core.Entities.User", b =>
                {
                    b.Navigation("AIRecommendations");

                    b.Navigation("AiLogs");

                    b.Navigation("CreatedPromptTemplates");

                    b.Navigation("Member");

                    b.Navigation("SurveyResults");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CGG.Core.Entities.UserSurvey", b =>
                {
                    b.Navigation("AiLogs");

                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
